# Exported from Render on 2026-04-23T17:39:04Z
version: "1"
projects:
    - name: ABA Factory System
      environments:
          - name: Production
            services:
                - type: pserv
                  name: aba-factory-management-system-backend
                  runtime: node
                  repo: https://github.com/Factory-System/aba-factory-management-system
                  branch: prod
                  plan: free
                  envVars:
                      - key: JWT_SECRET
                        sync: false
                      - key: CLIENT_URL
                        sync: false
                      - key: NODE_ENV
                        sync: false
                      - key: COOKIE_KEY
                        sync: false
                      - key: MONGO_URI
                        sync: false
                      - key: PORT
                        sync: false
                  region: oregon
                  buildCommand: npm install
                  startCommand: npm start
                  autoDeployTrigger: commit
                  rootDir: backend
